title: ROR Development
description: Web development agency — Ruby on Rails, PHP, Mobile Apps, CRM/ERP
url: "https://ror-development.com"
baseurl: ""

contact_email: contact@ror-development.com
telegram: rordevelopment

languages: [en, ua, de, ru]
default_lang: en

markdown: kramdown

plugins:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
